# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Voucher APP | Next.js

on:
  push:
    branches: ["main"]
    paths-ignore: ["helm/**/*"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["helm/**/*"]

  workflow_dispatch:

env:
  CONTAINER_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/voucher-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%Y.%-m.%-d.%-H.%-M.%-S')" # this is the build number of our image as date

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push the image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.CONTAINER_NAME }}:${{ steps.build-number.outputs.BUILD_NUMBER }}
            ${{ env.CONTAINER_NAME }}:latest

      - name: Update values.yaml
        run: |
          cd helm
          sed -i 's|tag:.*|tag: '${{ steps.build-number.outputs.BUILD_NUMBER }}'|' values.yaml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
